import 'package:flutter_app_master/generated/json/base/json_convert_content.dart';
import 'package:flutter_app_master/generated/json/base/json_filed.dart';

class NewWorkerGetOrderListEntity with JsonConvert<NewWorkerGetOrderListEntity> {
	@JSONField(name: "StatusCode")
	int statusCode;
	@JSONField(name: "Info")
	String info;
	@JSONField(name: "Count")
	int count;
	@JSONField(name: "Data")
	NewWorkerGetOrderListData data;
}

class NewWorkerGetOrderListData with JsonConvert<NewWorkerGetOrderListData> {
	String code;
	String msg;
	String count;
	List<NewWorkerGetOrderListDataData> data;
}

class NewWorkerGetOrderListDataData with JsonConvert<NewWorkerGetOrderListDataData> {
	@JSONField(name: "Id")
	int id;
	@JSONField(name: "OrderID")
	int orderID;
	@JSONField(name: "TypeID")
	int typeID;
	@JSONField(name: "TypeName")
	String typeName;
	@JSONField(name: "SystemSendUser")
	dynamic systemSendUser;
	dynamic picture;
	@JSONField(name: "SubTypeID")
	int subTypeID;
	@JSONField(name: "Frozen")
	double frozen;
	@JSONField(name: "SubTypeName")
	dynamic subTypeName;
	@JSONField(name: "CategoryID")
	int categoryID;
	@JSONField(name: "CategoryName")
	dynamic categoryName;
	@JSONField(name: "SubCategoryID")
	int subCategoryID;
	@JSONField(name: "SubCategoryName")
	dynamic subCategoryName;
	@JSONField(name: "Memo")
	dynamic memo;
	@JSONField(name: "BrandID")
	int brandID;
	@JSONField(name: "BrandName")
	dynamic brandName;
	@JSONField(name: "SendAddress")
	dynamic sendAddress;
	@JSONField(name: "ProductType")
	dynamic productType;
	@JSONField(name: "ProductTypeID")
	int productTypeID;
	@JSONField(name: "Num")
	int num;
	@JSONField(name: "ProvinceCode")
	String provinceCode;
	@JSONField(name: "CityCode")
	String cityCode;
	@JSONField(name: "AreaCode")
	String areaCode;
	@JSONField(name: "DistrictCode")
	String districtCode;
	@JSONField(name: "WarrantyOrderId")
	dynamic warrantyOrderId;
	@JSONField(name: "ProvinceName")
	String provinceName;
	@JSONField(name: "CityName")
	String cityName;
	@JSONField(name: "AreaName")
	String areaName;
	@JSONField(name: "DistrictName")
	String districtName;
	@JSONField(name: "Address")
	String address;
	@JSONField(name: "FullAddress")
	String fullAddress;
	@JSONField(name: "Longitude")
	String longitude;
	@JSONField(name: "Dimension")
	String dimension;
	@JSONField(name: "UserID")
	String userID;
	@JSONField(name: "ComID")
	dynamic comID;
	@JSONField(name: "Guarantee")
	String guarantee;
	@JSONField(name: "UserName")
	String userName;
	@JSONField(name: "Phone")
	String phone;
	@JSONField(name: "CreateDate")
	String createDate;
	@JSONField(name: "AudDate")
	String audDate;
	@JSONField(name: "ReceiveOrderDate")
	dynamic receiveOrderDate;
	@JSONField(name: "RepairCompleteDate")
	dynamic repairCompleteDate;
	@JSONField(name: "AppraiseDate")
	dynamic appraiseDate;
	@JSONField(name: "State")
	String state;
	@JSONField(name: "FakerTime")
	int fakerTime;
	@JSONField(name: "AffiliatedPerson")
	int affiliatedPerson;
	@JSONField(name: "AlreadyArrived")
	dynamic alreadyArrived;
	@JSONField(name: "CurrentOperator")
	int currentOperator;
	@JSONField(name: "LastReturnVisitDate")
	dynamic lastReturnVisitDate;
	@JSONField(name: "StateHtml")
	String stateHtml;
	@JSONField(name: "Extra")
	dynamic extra;
	@JSONField(name: "ExtraTime")
	dynamic extraTime;
	@JSONField(name: "IsCall")
	dynamic isCall;
	@JSONField(name: "ExtraFee")
	double extraFee;
	@JSONField(name: "IsUse")
	String isUse;
	@JSONField(name: "SendUser")
	String sendUser;
	@JSONField(name: "OrgSendUser")
	dynamic orgSendUser;
	@JSONField(name: "LoginUser")
	String loginUser;
	@JSONField(name: "IsPay")
	String isPay;
	@JSONField(name: "OrderMoney")
	double orderMoney;
	double terraceMoney;
	@JSONField(name: "InitMoney")
	double initMoney;
	@JSONField(name: "ExamineMoney")
	double examineMoney;
	@JSONField(name: "AgainMoney")
	double againMoney;
	@JSONField(name: "MasterPrice")
	double masterPrice;
	@JSONField(name: "OtherMoney")
	double otherMoney;
	@JSONField(name: "RelationOrderID")
	int relationOrderID;
	@JSONField(name: "BeyondMoney")
	double beyondMoney;
	@JSONField(name: "QuaMoney")
	double quaMoney;
	@JSONField(name: "ParentMoney")
	double parentMoney;
	@JSONField(name: "BeyondID")
	int beyondID;
	@JSONField(name: "LeaveCount")
	int leaveCount;
	@JSONField(name: "BeyondState")
	dynamic beyondState;
	@JSONField(name: "BeyondDistance")
	String beyondDistance;
	@JSONField(name: "Accessory")
	dynamic accessory;
	@JSONField(name: "AccessorySequency")
	dynamic accessorySequency;
	@JSONField(name: "AccessoryApplyState")
	dynamic accessoryApplyState;
	@JSONField(name: "AccessoryAndServiceApplyState")
	dynamic accessoryAndServiceApplyState;
	@JSONField(name: "AccessoryState")
	dynamic accessoryState;
	@JSONField(name: "AccessorySendState")
	String accessorySendState;
	@JSONField(name: "AccessoryMoney")
	double accessoryMoney;
	@JSONField(name: "AccessorySearchState")
	dynamic accessorySearchState;
	@JSONField(name: "AccessoryApplyDate")
	dynamic accessoryApplyDate;
	@JSONField(name: "AccessoryMemo")
	dynamic accessoryMemo;
	@JSONField(name: "AccessoryServiceMoney")
	double accessoryServiceMoney;
	@JSONField(name: "Service")
	dynamic service;
	@JSONField(name: "ServiceMoney")
	double serviceMoney;
	@JSONField(name: "ServiceApplyState")
	dynamic serviceApplyState;
	@JSONField(name: "ServiceApplyDate")
	dynamic serviceApplyDate;
	@JSONField(name: "AccessoryAndServiceApplyDate")
	dynamic accessoryAndServiceApplyDate;
	@JSONField(name: "StarOrder")
	dynamic starOrder;
	@JSONField(name: "FStarOrder")
	dynamic fStarOrder;
	@JSONField(name: "PostPayType")
	dynamic postPayType;
	@JSONField(name: "PostMoney")
	double postMoney;
	@JSONField(name: "NewMoney")
	dynamic newMoney;
	@JSONField(name: "AddressBack")
	dynamic addressBack;
	@JSONField(name: "IsReturn")
	dynamic isReturn;
	@JSONField(name: "ApplyNum")
	int applyNum;
	@JSONField(name: "QApplyNum")
	int qApplyNum;
	@JSONField(name: "MallID")
	int mallID;
	@JSONField(name: "EndRemark")
	dynamic endRemark;
	@JSONField(name: "Grade")
	int grade;
	@JSONField(name: "Grade1")
	int grade1;
	@JSONField(name: "Grade2")
	int grade2;
	@JSONField(name: "Grade3")
	int grade3;
	@JSONField(name: "ReturnAccessory")
	dynamic returnAccessory;
	@JSONField(name: "ReturnAccessoryMsg")
	dynamic returnAccessoryMsg;
	@JSONField(name: "ApplyCancel")
	dynamic applyCancel;
	@JSONField(name: "OrgAppraise")
	dynamic orgAppraise;
	@JSONField(name: "UpdateTime")
	String updateTime;
	@JSONField(name: "LateTime")
	String lateTime;
	@JSONField(name: "IsExtraTime")
	dynamic isExtraTime;
	@JSONField(name: "OrderPayStr")
	dynamic orderPayStr;
	@JSONField(name: "ThirdPartyNo")
	dynamic thirdPartyNo;
	@JSONField(name: "PartyNo")
	dynamic partyNo;
	@JSONField(name: "ExpressNo")
	dynamic expressNo;
	@JSONField(name: "RecycleOrderHour")
	int recycleOrderHour;
	@JSONField(name: "IsRecevieGoods")
	String isRecevieGoods;
	@JSONField(name: "AppointmentMessage")
	dynamic appointmentMessage;
	@JSONField(name: "AppointmentState")
	dynamic appointmentState;
	@JSONField(name: "IsLate")
	dynamic isLate;
	@JSONField(name: "Distance")
	double distance;
	@JSONField(name: "DistanceTureOrFalse")
	bool distanceTureOrFalse;
	@JSONField(name: "SendOrderState")
	String sendOrderState;
	@JSONField(name: "SendOrderMsg")
	String sendOrderMsg;
	@JSONField(name: "IsSendRepair")
	dynamic isSendRepair;
	dynamic barCode;
	int barCodeIsNo;
	@JSONField(name: "OrderSource")
	dynamic orderSource;
	@JSONField(name: "WithdrawalId")
	int withdrawalId;
	@JSONField(name: "LeaveMessageState")
	dynamic leaveMessageState;
	dynamic appointmentTime;
	@JSONField(name: "OrderImg")
	List<dynamic> orderImg;
	@JSONField(name: "ReturnaccessoryImg")
	List<dynamic> returnaccessoryImg;
	@JSONField(name: "OrderAccessroyDetail")
	List<dynamic> orderAccessroyDetail;
	@JSONField(name: "OrderServiceDetail")
	List<dynamic> orderServiceDetail;
	@JSONField(name: "OrderBeyondImg")
	List<dynamic> orderBeyondImg;
	@JSONField(name: "OrderComplaintDetail")
	List<dynamic> orderComplaintDetail;
	@JSONField(name: "OrderAppraiseDetail")
	List<dynamic> orderAppraiseDetail;
	@JSONField(name: "SendOrderList")
	List<NewWorkerGetOrderListDataDataSendOrderList> sendOrderList;
	@JSONField(name: "LeavemessageList")
	List<dynamic> leavemessageList;
	@JSONField(name: "LeavemessageimgList")
	List<dynamic> leavemessageimgList;
	@JSONField(name: "IsPressFactory")
	dynamic isPressFactory;
	@JSONField(name: "WorkerComplaint")
	dynamic workerComplaint;
	@JSONField(name: "FactoryComplaint")
	dynamic factoryComplaint;
	@JSONField(name: "Identification")
	dynamic identification;
	@JSONField(name: "IsRetuenVisit")
	dynamic isRetuenVisit;
	@JSONField(name: "OrderRecord")
	dynamic orderRecord;
	@JSONField(name: "ArtisanPhone")
	dynamic artisanPhone;
	@JSONField(name: "IsLook")
	String isLook;
	@JSONField(name: "FIsLook")
	String fIsLook;
	@JSONField(name: "IsNoMaster")
	dynamic isNoMaster;
	@JSONField(name: "CustomerUserId")
	dynamic customerUserId;
	@JSONField(name: "CompanyName")
	dynamic companyName;
	@JSONField(name: "WorkerTrueName")
	dynamic workerTrueName;
	@JSONField(name: "BackstageGetOrderListState")
	dynamic backstageGetOrderListState;
	int page;
	int limit;
	@JSONField(name: "StateList")
	List<dynamic> stateList;
	List<dynamic> subAccountList;
	@JSONField(name: "AccessorySearchStateList")
	dynamic accessorySearchStateList;
	@JSONField(name: "EndTime")
	dynamic endTime;
	@JSONField(name: "StartTime")
	dynamic startTime;
	@JSONField(name: "AppointmentTimeStart")
	dynamic appointmentTimeStart;
	@JSONField(name: "AppointmentTimeEnd")
	dynamic appointmentTimeEnd;
	int isOnLookMessage;
	@JSONField(name: "AppointmentRefuseState")
	dynamic appointmentRefuseState;
	@JSONField(name: "InvoiceName")
	dynamic invoiceName;
	@JSONField(name: "AccessoryRefuseState")
	dynamic accessoryRefuseState;
	@JSONField(name: "FactoryApplyState")
	dynamic factoryApplyState;
	@JSONField(name: "OrderApplyState")
	dynamic orderApplyState;
	@JSONField(name: "AccessoryIsPay")
	dynamic accessoryIsPay;
	@JSONField(name: "OrderSort")
	dynamic orderSort;
	dynamic partsIs;
	dynamic messageIs;
	@JSONField(name: "SendUserIs")
	dynamic sendUserIs;
	@JSONField(name: "SelectCustomerUserId")
	dynamic selectCustomerUserId;
	dynamic uniqId;
	@JSONField(name: "IsSettlement")
	dynamic isSettlement;
	@JSONField(name: "SettlementMoney")
	double settlementMoney;
	@JSONField(name: "SettlementTime")
	dynamic settlementTime;
	@JSONField(name: "OrderAccessoryStr")
	dynamic orderAccessoryStr;
	@JSONField(name: "ContinueIssuing")
	dynamic continueIssuing;
	@JSONField(name: "ProdModelName")
	dynamic prodModelName;
	@JSONField(name: "ProdModelID")
	int prodModelID;
	@JSONField(name: "TrueName")
	dynamic trueName;
	@JSONField(name: "NickName")
	dynamic nickName;
	@JSONField(name: "CancelAndCloseTime")
	dynamic cancelAndCloseTime;
	@JSONField(name: "CompleteTime")
	dynamic completeTime;
	@JSONField(name: "IsApplicationAccessory")
	bool isApplicationAccessory;
	@JSONField(name: "MasterIsLookFee")
	bool masterIsLookFee;
	@JSONField(name: "IsSignIn")
	int isSignIn;
	@JSONField(name: "OrderProductModels")
	List<NewWorkerGetOrderListDataDataOrderProductModel> orderProductModels;
	@JSONField(name: "OrderRemoteFeeDetail")
	dynamic orderRemoteFeeDetail;
	@JSONField(name: "Version")
	int version;
}

class NewWorkerGetOrderListDataDataSendOrderList with JsonConvert<NewWorkerGetOrderListDataDataSendOrderList> {
	@JSONField(name: "Id")
	int id;
	@JSONField(name: "SendID")
	int sendID;
	@JSONField(name: "CreateDate")
	String createDate;
	@JSONField(name: "UserID")
	String userID;
	@JSONField(name: "OrderID")
	int orderID;
	@JSONField(name: "State")
	String state;
	@JSONField(name: "UpdateDate")
	dynamic updateDate;
	@JSONField(name: "ServiceDate")
	dynamic serviceDate;
	@JSONField(name: "ServiceDate2")
	dynamic serviceDate2;
	@JSONField(name: "LoginUser")
	String loginUser;
	@JSONField(name: "IsUse")
	String isUse;
	@JSONField(name: "CategoryID")
	int categoryID;
	@JSONField(name: "CategoryName")
	dynamic categoryName;
	@JSONField(name: "SubTypeID")
	int subTypeID;
	@JSONField(name: "SubTypeName")
	dynamic subTypeName;
	@JSONField(name: "Memo")
	dynamic memo;
	@JSONField(name: "BrandID")
	int brandID;
	@JSONField(name: "BrandName")
	dynamic brandName;
	@JSONField(name: "ProductType")
	dynamic productType;
	@JSONField(name: "ProvinceCode")
	dynamic provinceCode;
	@JSONField(name: "CityCode")
	dynamic cityCode;
	@JSONField(name: "AreaCode")
	dynamic areaCode;
	@JSONField(name: "Address")
	dynamic address;
	@JSONField(name: "Guarantee")
	dynamic guarantee;
	@JSONField(name: "UserName")
	dynamic userName;
	@JSONField(name: "Phone")
	dynamic phone;
	@JSONField(name: "AppointmentState")
	dynamic appointmentState;
	@JSONField(name: "AppointmentMessage")
	dynamic appointmentMessage;
	@JSONField(name: "IsAutoDispatch")
	int isAutoDispatch;
	@JSONField(name: "IsSignIn")
	int isSignIn;
	int page;
	int limit;
	@JSONField(name: "Version")
	int version;
}

class NewWorkerGetOrderListDataDataOrderProductModel with JsonConvert<NewWorkerGetOrderListDataDataOrderProductModel> {
	@JSONField(name: "Id")
	int id;
	@JSONField(name: "OrderProdcutID")
	int orderProdcutID;
	@JSONField(name: "OrderID")
	int orderID;
	@JSONField(name: "CategoryID")
	int categoryID;
	@JSONField(name: "CategoryName")
	String categoryName;
	@JSONField(name: "SubCategoryID")
	int subCategoryID;
	@JSONField(name: "SubCategoryName")
	String subCategoryName;
	@JSONField(name: "ProductTypeID")
	int productTypeID;
	@JSONField(name: "ProductType")
	String productType;
	@JSONField(name: "ProdModelID")
	int prodModelID;
	@JSONField(name: "ProdModelName")
	String prodModelName;
	@JSONField(name: "Memo")
	String memo;
	@JSONField(name: "CreateDate")
	String createDate;
	@JSONField(name: "AudDate")
	dynamic audDate;
	@JSONField(name: "ReceiveOrderDate")
	dynamic receiveOrderDate;
	@JSONField(name: "RepairCompleteDate")
	dynamic repairCompleteDate;
	@JSONField(name: "AppraiseDate")
	dynamic appraiseDate;
	@JSONField(name: "State")
	dynamic state;
	@JSONField(name: "SendUser")
	dynamic sendUser;
	@JSONField(name: "OrderProdMoney")
	double orderProdMoney;
	@JSONField(name: "InitMoney")
	double initMoney;
	@JSONField(name: "BeyondMoney")
	double beyondMoney;
	@JSONField(name: "TechnologyServiceMoney")
	double technologyServiceMoney;
	@JSONField(name: "PostMoney")
	double postMoney;
	@JSONField(name: "FactorySettlementMoney")
	double factorySettlementMoney;
	@JSONField(name: "AgainMoney")
	double againMoney;
	@JSONField(name: "MasterPrice")
	double masterPrice;
	@JSONField(name: "OtherMoney")
	double otherMoney;
	double terraceMoney;
	@JSONField(name: "MWSettlementMoney")
	double mWSettlementMoney;
	@JSONField(name: "BrandID")
	int brandID;
	@JSONField(name: "BrandName")
	String brandName;
	dynamic accessory;
	List<dynamic> accessoryData;
	@JSONField(name: "SizeID")
	int sizeID;
	@JSONField(name: "FrozenMoney")
	double frozenMoney;
	@JSONField(name: "IsUse")
	String isUse;
	@JSONField(name: "Num")
	int num;
	@JSONField(name: "RelationParentProdID")
	int relationParentProdID;
	@JSONField(name: "ProductState")
	int productState;
	@JSONField(name: "EndRemark")
	dynamic endRemark;
	@JSONField(name: "RepairExplain")
	dynamic repairExplain;
	@JSONField(name: "BarCode")
	dynamic barCode;
	@JSONField(name: "Explains")
	dynamic explains;
	@JSONField(name: "EndImgUrls")
	List<dynamic> endImgUrls;
	@JSONField(name: "Version")
	int version;
}
