import 'package:flutter_app_master/generated/json/base/json_convert_content.dart';
import 'package:flutter_app_master/generated/json/base/json_filed.dart';

class UserinfoEntity with JsonConvert<UserinfoEntity> {
	@JSONField(name: "StatusCode")
	int statusCode;
	@JSONField(name: "Info")
	String info;
	@JSONField(name: "Count")
	int count;
	@JSONField(name: "Data")
	UserinfoData data;
}

class UserinfoData with JsonConvert<UserinfoData> {
	String code;
	String msg;
	String count;
	List<UserinfoDataData> data;
}

class UserinfoDataData with JsonConvert<UserinfoDataData> {
	@JSONField(name: "Id")
	String id;
	@JSONField(name: "UserID")
	String userID;
	@JSONField(name: "NickName")
	String nickName;
	@JSONField(name: "Avator")
	String avator;
	@JSONField(name: "CreateDate")
	String createDate;
	@JSONField(name: "LastLoginDate")
	String lastLoginDate;
	@JSONField(name: "LoginCount")
	int loginCount;
	@JSONField(name: "RemainMoney")
	double remainMoney;
	@JSONField(name: "TotalMoney")
	double totalMoney;
	@JSONField(name: "FrozenMoney")
	double frozenMoney;
	@JSONField(name: "Type")
	String type;
	@JSONField(name: "TopRank")
	String topRank;
	@JSONField(name: "YnAuth")
	dynamic ynAuth;
	dynamic barCode;
	@JSONField(name: "IsUse")
	String isUse;
	@JSONField(name: "PassWord")
	String passWord;
	@JSONField(name: "PayPassWord")
	String payPassWord;
	@JSONField(name: "RoleID")
	int roleID;
	@JSONField(name: "RoleName")
	String roleName;
	@JSONField(name: "AccountID")
	int accountID;
	@JSONField(name: "GreenTopRank")
	int greenTopRank;
	@JSONField(name: "DistrictCode")
	String districtCode;
	@JSONField(name: "Con")
	int con;
	@JSONField(name: "Longitude")
	String longitude;
	@JSONField(name: "Dimension")
	String dimension;
	@JSONField(name: "ServiceTotalOrderNum")
	String serviceTotalOrderNum;
	@JSONField(name: "ServiceComplaintNum")
	String serviceComplaintNum;
	@JSONField(name: "UnfinishedAmount")
	double unfinishedAmount;
	@JSONField(name: "ServiceTotalMoney")
	double serviceTotalMoney;
	@JSONField(name: "CompanyName")
	String companyName;
	@JSONField(name: "OrderFee")
	double orderFee;
	@JSONField(name: "FeeTypes")
	dynamic feeTypes;
	@JSONField(name: "DoorFee")
	double doorFee;
	@JSONField(name: "AgainMoney")
	double againMoney;
	@JSONField(name: "PlatformFee")
	double platformFee;
	@JSONField(name: "IsOnLine")
	int isOnLine;
	@JSONField(name: "StartDate")
	dynamic startDate;
	@JSONField(name: "EndDate")
	dynamic endDate;
	@JSONField(name: "ProvinceCode")
	String provinceCode;
	@JSONField(name: "CityCode")
	String cityCode;
	@JSONField(name: "AreaCode")
	String areaCode;
	@JSONField(name: "Address")
	String address;
	@JSONField(name: "DepositMoney")
	double depositMoney;
	@JSONField(name: "DepositFrozenMoney")
	double depositFrozenMoney;
	@JSONField(name: "Skills")
	dynamic skills;
	@JSONField(name: "IfAuth")
	String ifAuth;
	@JSONField(name: "AuthMessage")
	String authMessage;
	@JSONField(name: "ParentUserID")
	dynamic parentUserID;
	@JSONField(name: "TrueName")
	String trueName;
	@JSONField(name: "IDCard")
	String iDCard;
	@JSONField(name: "Sex")
	String sex;
	@JSONField(name: "Phone")
	String phone;
	dynamic emergencyContact;
	int teamNumber;
	@JSONField(name: "IsOrNoTruck")
	dynamic isOrNoTruck;
	int page;
	int limit;
	@JSONField(name: "Version")
	int version;
}
